### ISSUE TITLE
Use Apache 2.0

### ISSUE THREAD

**Issue by haohanyang** [Darkatse/Teacat#1]
https://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by Darkatse** [comment]
In fact, I didn't really think too much about choosing licences, I just chose GPL-3.0 out of support for open source - you know, the GPL is “infectious” and a bunch of famous projects use GPL licences, I guess.

But I'd be happy to hear advice on why to switch to Apache though, after all, I'm really not an expert on the subject :D

**Comment by haohanyang** [comment]
Thanks for being open to discussing this! It's great you're passionate
about open source. GPL-3.0 is definitely a strong choice, and like you
said, it's used by many great projects.

I was thinking about Apache 2.0 for a couple of reasons that might be
beneficial for your project in the long run:

   -

   *Commercial Friendliness:* Apache 2.0 is very permissive when it comes
   to commercial use and modification. It allows companies to integrate your
   project into their products without requiring them to open source their
   entire codebase. This can lead to:
   -

      *Wider Adoption:* More companies might be willing to use and
      contribute to the project.
      -

      *Increased Contributions:* You might get contributions from
      developers working at companies that prefer Apache 2.0.
      -

   *Patent Protection:* Apache 2.0 includes strong patent language that
   benefits both contributors and users. This can provide peace of mind,
   especially if your project gains traction.
   -

   *Easy Integration:* Apache 2.0 is very simple to comply with. It doesn't
   have the "infectious" nature of GPL (which requires derivative works to
   also be GPL), making it easier to integrate your project with others.

I completely understand you chose GPL-3.0 out of support for open source,
and those values are important! The great thing is, Apache 2.0 strongly
aligns with those same values while potentially opening the door to wider
adoption and contributions.

Would you be open to reading a bit more about Apache 2.0? I'm happy to
share some resources and we can chat about whether it might be a good fit.
Ultimately, the choice is yours, and I want to respect whatever you feel is
best for the project's future!

Best,

**Comment by Darkatse** [comment]
Hey, you cannot just use AI to answer my question, that's not fair! I just want to know _your_ own opinions.

But alright, I may consider to switch on Apache License later, since I'm not really stick on GPL.
